Repository operate-first/opfcli, pull requests merged in 2021-05, with the labels that each got.

#2 update the prow resource limits
  .prow.yaml
Labels: approved, lgtm

#1 initial import of opfcli command line tool
  .gitignore
  .pre-commit-config.yaml
  Makefile
  README.md
  cmd/api.go
  cmd/createGroup.go
  cmd/createGroup_test.go
  cmd/createProject.go
  cmd/createProject_test.go
  cmd/enableMonitoring.go
  cmd/enableMonitoring_test.go
  cmd/grantAccess.go
  cmd/grantAccess_test.go
  cmd/main.go
  cmd/main_test.go
  cmd/testdata/createGroup/cluster-scope/base/user.openshift.io/groups/testgroup/group.yaml
  cmd/testdata/createGroup/cluster-scope/base/user.openshift.io/groups/testgroup/kustomization.yaml
  cmd/testdata/createProject/cluster-scope/base/core/namespaces/testproject/kustomization.yaml
  cmd/testdata/createProject/cluster-scope/base/core/namespaces/testproject/namespace.yaml
  cmd/testdata/createProject/cluster-scope/base/user.openshift.io/groups/testgroup/group.yaml
  cmd/testdata/createProject/cluster-scope/base/user.openshift.io/groups/testgroup/kustomization.yaml
  cmd/testdata/createProject/cluster-scope/components/project-admin-rolebindings/testgroup/kustomization.yaml
  cmd/testdata/createProject/cluster-scope/components/project-admin-rolebindings/testgroup/rbac.yaml
  cmd/testdata/enableMonitoring/cluster-scope/base/core/namespaces/testproject/kustomization.yaml
  cmd/testdata/enableMonitoring/cluster-scope/base/core/namespaces/testproject/namespace.yaml
  cmd/testdata/enableMonitoring/cluster-scope/base/user.openshift.io/groups/testgroup/group.yaml
  cmd/testdata/enableMonitoring/cluster-scope/base/user.openshift.io/groups/testgroup/kustomization.yaml
  cmd/testdata/enableMonitoring/cluster-scope/components/monitoring-rbac/kustomization.yaml
  cmd/testdata/enableMonitoring/cluster-scope/components/project-admin-rolebindings/testgroup/kustomization.yaml
  cmd/testdata/enableMonitoring/cluster-scope/components/project-admin-rolebindings/testgroup/rbac.yaml
  cmd/testdata/grantAccess/cluster-scope/base/core/namespaces/testproject/kustomization.yaml
  cmd/testdata/grantAccess/cluster-scope/base/core/namespaces/testproject/namespace.yaml
  cmd/testdata/grantAccess/cluster-scope/base/user.openshift.io/groups/testgroup/group.yaml
  cmd/testdata/grantAccess/cluster-scope/base/user.openshift.io/groups/testgroup/kustomization.yaml
  cmd/testdata/grantAccess/cluster-scope/base/user.openshift.io/groups/testgroup2/group.yaml
  cmd/testdata/grantAccess/cluster-scope/base/user.openshift.io/groups/testgroup2/kustomization.yaml
  cmd/testdata/grantAccess/cluster-scope/components/project-admin-rolebindings/testgroup/kustomization.yaml
  cmd/testdata/grantAccess/cluster-scope/components/project-admin-rolebindings/testgroup/rbac.yaml
  cmd/testdata/grantAccess/cluster-scope/components/project-admin-rolebindings/testgroup2/kustomization.yaml
  cmd/testdata/grantAccess/cluster-scope/components/project-admin-rolebindings/testgroup2/rbac.yaml
  cmd/version.go
  go.mod
  go.sum
  main.go
  models/group.go
  models/kustomization.go
  models/main.go
  models/namespace.go
  models/resource.go
  models/rolebinding.go
  utils/fileutils.go
  utils/gitutils.go
  utils/kustomize.go
  utils/main.go
  version/main.go
Labels: approved, lgtm, size/XXL

#7 setup thoth release bot for opfcli
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/major-release.md
  .github/ISSUE_TEMPLATE/minor-release.md
  .github/ISSUE_TEMPLATE/patch-release.md
  .thoth.yaml
  version.py
Labels: approved, lgtm, size/L
