Repository operate-first/opfcli, pull requests merged in 2021-06, with the labels that each got.

#12 Add workflows for running pre-commit tests and building releases
  .github/workflows/precommit.yml
  .github/workflows/release.yml
  .golangci.yaml
  .pre-commit-config.yaml
  .prow.yaml
  .yamllint.yaml
  Makefile
  README.md
Labels: approved, lgtm, size/L

#13 Add tests for cmd module
  Makefile
  cmd/createGroup_test.go
  cmd/createProject_test.go
  cmd/enableMonitoring_test.go
  cmd/grantAccess_test.go
  cmd/main.go
  cmd/main_test.go
Labels: approved, lgtm, size/L

#15 Build image now uses ubi8 instead of Fedora 34
  .github/workflows/precommit.yml
  .github/workflows/release.yml
Labels: approved, lgtm, size/XS

#16 Build image now *really* uses ubi8 instead of Fedora 34 (#15)
  .github/workflows/release.yml
Labels: approved, lgtm, size/XS

#20 fix: Allow namespace creation if group already exists
  api/CreateProject.go
  api/CreateProject_test.go
  cmd/createProject_test.go
Labels: approved, lgtm, size/M

#21 chore: Remove ODH and OCP from bug template
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: approved, lgtm, size/XS

#36 feat: Enable cobra completion
  cmd/completion.go
  cmd/main.go
Labels: approved, lgtm, size/M

#22 Add install-operator command
  api/AddComponent_test.go
  api/CreateNamespace.go
  api/CreateNamespace_test.go
  api/CreateOperatorGroup.go
  api/CreateOperatorGroup_test.go
  api/CreateProject.go
  api/CreateSubscription.go
  api/CreateSubscription_test.go
  api/testdata/CreateOperatorGroup/cluster-scope/base/operators.coreos.com/operatorgroups/testproject/kustomization.yaml
  api/testdata/CreateOperatorGroup/cluster-scope/base/operators.coreos.com/operatorgroups/testproject/operatorgroup.yaml
  api/testdata/CreateOperatorGroupSingleNamespace/cluster-scope/base/operators.coreos.com/operatorgroups/testproject/kustomization.yaml
  api/testdata/CreateOperatorGroupSingleNamespace/cluster-scope/base/operators.coreos.com/operatorgroups/testproject/operatorgroup.yaml
  api/testdata/CreateSubscription/cluster-scope/base/operators.coreos.com/subscriptions/testoperator/kustomization.yaml
  api/testdata/CreateSubscription/cluster-scope/base/operators.coreos.com/subscriptions/testoperator/subscription.yaml
  api/testdata/CreateSubscriptionChannel/cluster-scope/base/operators.coreos.com/subscriptions/testoperator/kustomization.yaml
  api/testdata/CreateSubscriptionChannel/cluster-scope/base/operators.coreos.com/subscriptions/testoperator/subscription.yaml
  api/testdata/CreateSubscriptionManual/cluster-scope/base/operators.coreos.com/subscriptions/testoperator/kustomization.yaml
  api/testdata/CreateSubscriptionManual/cluster-scope/base/operators.coreos.com/subscriptions/testoperator/subscription.yaml
  cmd/installOperator.go
  cmd/installOperator_test.go
  cmd/main.go
  constants/main.go
  models/kustomization.go
  models/operatorgroup.go
  models/subscription.go
Labels: approved, lgtm, size/XL

#39 remove ipolonsk from owners
  OWNERS
Labels: approved, lgtm, size/XS

#40 fix: Namespace should be set in kustomizations
  api/CreateGroup.go
  api/CreateNamespace.go
  api/CreateOperatorGroup.go
  api/CreateSubscription.go
  api/testdata/AddComponent/cluster-scope/base/core/namespaces/testproject/kustomization.yaml
  api/testdata/AddGroupRBAC/cluster-scope/base/core/namespaces/testproject/kustomization.yaml
  api/testdata/CreateNamespace/cluster-scope/base/core/namespaces/testproject/kustomization.yaml
  api/testdata/CreateNamespaceNoLimitrange/cluster-scope/base/core/namespaces/testproject/kustomization.yaml
  api/testdata/CreateNamespaceQuota/cluster-scope/base/core/namespaces/testproject/kustomization.yaml
  api/testdata/CreateProject/cluster-scope/base/core/namespaces/testproject/kustomization.yaml
  models/kustomization.go
  utils/kustomize.go
Labels: approved, lgtm, size/S

#42 change description flag to display-name in create-project
  api/AddGroupRBAC_test.go
  api/CreateNamespace.go
  api/CreateNamespace_test.go
  api/CreateProject.go
  api/CreateProject_test.go
  api/testdata/AddGroupRBAC/cluster-scope/base/core/namespaces/testproject/namespace.yaml
  api/testdata/CreateNamespace/cluster-scope/base/core/namespaces/testproject/namespace.yaml
  api/testdata/CreateProject/cluster-scope/base/core/namespaces/testproject/namespace.yaml
  cmd/createProject.go
  models/namespace.go
Labels: approved, lgtm, size/M
